# Environment file for GIMP Notebooks
name: greenlandMapping
#
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask
  - datashader
  - fsspec
  - gdal
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - jupyter-panel-proxy
  - jupyterlab>=3
  - nbgitpuller
  - panel
  - param
  - pip
  - progressbar2
  - qgis
  - rasterio
  - rioxarray
  - stackstac
  - pip:
    - git+https://github.com/fastice/gimpfunc.git@master
    - git+https://github.com/fastice/gimpqgis.git@master
    - git+https://github.com/fastice/nisardev.git@main
    - git+http://github.com/developmentseed/rio-stac@master
    
    
